package org.stypox.dicio.ui.home

import android.app.Application
import androidx.compose.material3.SnackbarHostState
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.launch
import org.stypox.dicio.di.SkillContextInternal
import org.stypox.dicio.di.SpeechOutputDeviceWrapper
import org.stypox.dicio.di.SttInputDeviceWrapper
import org.stypox.dicio.eval.SkillEvaluator
import org.stypox.dicio.eval.SkillHandler
import org.stypox.dicio.io.input.SttState
import org.stypox.dicio.io.speech.SnackbarSpeechDevice
import javax.inject.Inject

@HiltViewModel
class HomeScreenViewModel @Inject constructor(
    application: Application,
    val skillContext: SkillContextInternal,
    val skillHandler: SkillHandler,
    val sttInputDevice: SttInputDeviceWrapper,
    val speechOutputDevice: SpeechOutputDeviceWrapper,
    val skillEvaluator: SkillEvaluator,
    // always instantiated, but does nothing if not the chosen speech device
    snackbarSpeechDevice: SnackbarSpeechDevice,
) : AndroidViewModel(application) {

    private var showSnackbarJob: Job? = null
    val snackbarHostState = SnackbarHostState()

    init {
        // show snackbars generated by the SnackbarSpeechDevice
        viewModelScope.launch {
            snackbarSpeechDevice.events.collect {
                if (it == null) {
                    showSnackbarJob?.cancel()
                } else {
                    showSnackbarJob?.cancel()
                    showSnackbarJob = launch {
                        snackbarHostState.showSnackbar(it)
                    }
                }
            }
        }

        // stop speaking when the STT device starts listening
        viewModelScope.launch {
            sttInputDevice.uiState
                .filter { it == SttState.Listening }
                .collect { speechOutputDevice.stopSpeaking() }
        }
    }
}
